### Instructions for Docker
## build image from this dockerfile. E.g. IMAGE_NAME = mnist, IMAGE_TAG = latest
# docker build -t <IMAGE_NAME>:<IMAGE_TAG> .
# e.g. docker build -t mnist:latest .


# FROM ubuntu:18.04
FROM nvidia/cuda:11.4.1-runtime-ubuntu18.04
SHELL ["/bin/bash", "-c"]
USER root

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1


# ==============================
# Replace with local SG mirrors
# ==============================
RUN sed --in-place --regexp-extended "s/(\/\/)(archive\.ubuntu)/\1sg.\2/" /etc/apt/sources.list
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ Asia/Singapore
RUN apt-get update
RUN apt-get install -y --no-install-recommends sudo curl tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && sudo dpkg-reconfigure -f noninteractive tzdata


# ============================== 
# User Setup
# ==============================
# add a user with the same USERID as the user outside the container
# Requires a docker build argument `USERID`
ARG USERID=1000
ENV USERNAME dev
ENV USER=dev
RUN useradd -U $USERNAME --uid $USERID -ms /bin/bash \
 && echo "$USERNAME:$USERNAME" | chpasswd \
 && adduser $USERNAME sudo \
 && echo "$USERNAME ALL=NOPASSWD: ALL" >> /etc/sudoers.d/$USERNAME
RUN sudo chown --recursive $USERNAME:$USERNAME /home
# Commands below run as the dev user
USER $USERNAME
WORKDIR /home


# ===============================
# Install General Tools
# ===============================
RUN sudo apt-get update --no-install-recommends \
&& sudo apt-get install -y \
	software-properties-common \
	git  \
	wget \
	zip \
	unzip \
	gedit \
	vim \
	python3-pip \
	python3-dev \
	nano

# update pip3 version
RUN sudo -H pip3 install --upgrade pip


# ===============================
# Install Dependencies
# ===============================
ADD requirements.txt .
RUN python3 -m pip install -r requirements.txt


# ==========================
# Cleanup
# ==========================
RUN sudo apt-get clean autoremove


# =================================== 
# Set working directory for container
# =================================== 
# /home
WORKDIR /home
